#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;

sub usage {
	print "$0: Initialize a Topology Service database\n";
	print "  --directory: The directory to hold the database\n";
}

my $db_config =<<EOC
set_lock_timeout 5000
set_txn_timeout 5000
set_lk_max_lockers 500000
set_lk_max_locks 500000
set_lk_max_objects 500000
set_lk_detect DB_LOCK_MINLOCKS
set_cachesize 0 67108864 0
set_flags DB_LOG_AUTOREMOVE
set_lg_regionmax 2097152
EOC
;

my $DB_DIRECTORY;
my $HELP;
my $status = GetOptions (
        'directory|d=s' => \$DB_DIRECTORY,
        'help|h' => \$HELP,
        );

if (not $status or $HELP) {
	usage();
	exit(0);
}

if (not $DB_DIRECTORY) {
	print "Error: No database directory specified\n";
	usage();
	exit(-1);
}

if (! -d $DB_DIRECTORY) {
	my $n = system("mkdir -p $DB_DIRECTORY");
	if ($n != 0) {
		print "Error: could not create directory $DB_DIRECTORY\n";
		exit(-2);
	}
}

open(DB_CONFIG, ">", $DB_DIRECTORY."/DB_CONFIG");
print DB_CONFIG $db_config;
close(DB_CONFIG);
