# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Base
version:      0.06
version_from: 
installdirs:  site
requires:
    Data::Compare:                 0.09
    Error::Simple:                 0
    Exporter:                      0
    IO::File:                      0
    Log::Log4perl:                 1
    LWP::UserAgent:                2.032
    Params::Validate:              0.7
    strict:                        0
    Test::More:                    0
    Time::HiRes:                   1.85
    warnings:                      0
    XML::LibXML:                   1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
