# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Base
version:      0.092
version_from: 
installdirs:  site
requires:
    base:                          0
    Carp:                          0
    Data::Compare:                 0.09
    Data::Dumper:                  2.101
    Error:                         0
    Exporter:                      0
    fields:                        0
    IO::File:                      0
    Log::Log4perl:                 1
    LWP::UserAgent:                2.032
    Params::Validate:              0.7
    strict:                        0
    Test::More:                    0
    Time::HiRes:                   1.85
    version:                       0
    warnings:                      0
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
