# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Status-Common
version:      0.09
version_from: lib/perfSONAR_PS/Status/Common.pm
installdirs:  site
requires:
    base:                          0
    Exporter:                      0
    fields:                        0
    Log::Log4perl:                 1
    strict:                        0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
