# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Client-LS-Remote
version:      v0.01
version_from: lib/perfSONAR_PS/Client/LS/Remote.pm
installdirs:  site
requires:
    Log::Log4perl:                 1
    perfSONAR_PS::Client::Echo:    v0.01
    perfSONAR_PS::Common:          v0.01
    perfSONAR_PS::Messages:        v0.01
    perfSONAR_PS::Transport:       v0.01
    strict:                        0
    version:                       0.5
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
