# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Services-MA-Topology
version:      0.06
version_from: lib/perfSONAR_PS/Services/MA/Topology.pm
installdirs:  site
requires:
    File::Basename:                0
    Getopt::Long:                  0
    Log::Log4perl:                 1
    perfSONAR_PS::Client::LS::Remote: 0.06
    perfSONAR_PS::Client::Topology::MA: 0.06
    perfSONAR_PS::Client::Topology::XMLDB: 0.06
    perfSONAR_PS::Common:          0.06
    perfSONAR_PS::Messages:        0.06
    perfSONAR_PS::Services::Base:  0.06
    perfSONAR_PS::Topology::Common: 0.06
    perfSONAR_PS::Topology::ID:    0.06
    strict:                        0
    warnings:                      0
    XML::LibXML:                   1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
