# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Services-MA-Topology
version:      v0.01
version_from: lib/perfSONAR_PS/Services/MA/Topology.pm
installdirs:  site
requires:
    File::Basename:                0
    Getopt::Long:                  0
    Log::Log4perl:                 1
    perfSONAR_PS::Client::LS::Remote: v0.01
    perfSONAR_PS::Client::Topology::MA: v0.01
    perfSONAR_PS::Client::Topology::XMLDB: v0.01
    perfSONAR_PS::Common:          v0.01
    perfSONAR_PS::Messages:        v0.01
    perfSONAR_PS::Services::Base:  v0.01
    perfSONAR_PS::Topology::Common: v0.01
    perfSONAR_PS::Topology::ID:    v0.01
    strict:                        0
    version:                       0.5
    warnings:                      0
    XML::LibXML:                   1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
