#!/bin/bash
#
# Init file for perfSONAR Traceroute On-Demand MP Service
#
# chkconfig: 2345 60 20
# description: perfSONAR Traceroute On-Demand MP Service
#

PREFIX=/opt/perfsonar_ps/traceroute_ma
BINDIR=${PREFIX}/bin
CONFDIR=${PREFIX}/etc
RUNDIR=/var/run

CONFFILE=${CONFDIR}/ondemand_mp-daemon.conf
LOGGERFILE=${CONFDIR}/ondemand_mp-daemon_logger.conf
PIDFILE=traceroute_ondemand_mp.pid

USER=perfsonar
GROUP=perfsonar

FULL_PIDFILE=${RUNDIR}/${PIDFILE}

PERFSONAR="${BINDIR}/daemon.pl --config=${CONFFILE} --pidfile=${PIDFILE} --piddir=${RUNDIR} --logger=${LOGGERFILE} --user=${USER} --group=${GROUP}"

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    # check for pidfile
    if [ -f $FULL_PIDFILE ] ; then
        PID=`cat $FULL_PIDFILE`
        if [ "x$PID" != "x" ] && kill -0 $PID 2>/dev/null ; then
            STATUS="perfSONAR Traceroute On-Demand MP Service (pid $PID) running"
            RUNNING=1
        else
            STATUS="perfSONAR Traceroute On-Demand MP Service (pid $PID?) not running"
            RUNNING=0
        fi
    else
        STATUS="perfSONAR Traceroute On-Demand MP Service (no pid file) not running"
        RUNNING=0
    fi 

    case $ARG in
    start)
	echo $PERFSONAR

	if $PERFSONAR ; then
	    echo "$0 $ARG: perfSONAR Traceroute On-Demand MP Service started"
	else
	    echo "$0 $ARG: perfSONAR Traceroute On-Demand MP Service could not be started"
	    ERROR=3
	fi
	;;
    stop)
	if [ $RUNNING -eq 0 ]; then
	    echo "$0 $ARG: $STATUS"
	    continue
	fi
	if kill $PID ; then
	    echo "$0 $ARG: perfSONAR Traceroute On-Demand MP Service stopped"
	else
	    echo "$0 $ARG: perfSONAR Traceroute On-Demand MP Service could not be stopped"
	    ERROR=4
	fi
	;;
    restart)
    	$0 stop; echo "waiting..."; sleep 10; $0 start;
	;;
    *)
	echo "usage: $0 (start|stop|restart|help)"
	cat <<EOF

start      - start perfSONAR Traceroute On-Demand MP Service
stop       - stop perfSONAR Traceroute On-Demand MP Service
restart    - restart perfSONAR Traceroute On-Demand MP Service if running by sending a SIGHUP or start if 
             not running
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR
