services:
    owamp: "http://ggf.org/ns/nmwg/characteristic/delay/summary/20070921"
serviceDisplayName:
    owamp: "One Way Latency"
hosts:
    localhost: "http://localhost:8085/perfSONAR_PS/services/pSB"


