Name:           perl-perfSONAR_PS-Services-MA-perfSONARBOUY
Version:        0.01
Release:        1%{?dist}
Summary:        perfSONAR_PS::Services::MA::perfSONARBOUY Perl module
License:        distributable, see LICENSE
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/perfSONAR_PS-Services-MA-perfSONARBOUY/
Source0:        http://www.cpan.org/modules/by-module/perfSONAR_PS/perfSONAR_PS-Services-MA-perfSONARBOUY-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(Log::Log4perl) >= 1
Requires:       perl(Module::Load) >= 0.1
Requires:       perl(perfSONAR_PS::Common) >= 0.06
Requires:       perl(perfSONAR_PS::DB::File) >= 0.06
Requires:       perl(perfSONAR_PS::DB::SQL) >= 0.06
Requires:       perl(perfSONAR_PS::Error_compat) >= 0.06
Requires:       perl(perfSONAR_PS::Messages) >= 0.06
Requires:       perl(perfSONAR_PS::Services::Base) >= 0.06
Requires:       perl(perfSONAR_PS::Services::MA::General) >= 0.06
Requires:       perl(perfSONAR_PS::Transport) >= 0.06
Requires:       perl(perfSONAR_PS::XML::Document_string) >= 0.06
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The perfSONAR_PS::Services::MA::perfSONARBOUY module allows one to make
BWCTL data available from backend SQL storage using the perfSONAR
perfSONARBOUY MA protocols.

%prep
%setup -q -n perfSONAR_PS-Services-MA-perfSONARBOUY-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null \;

chmod -R u+rwX,go+rX,go-w $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README perl-perfSONAR_PS-Services-MA-perfSONARBOUY.spec
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 28 2008 aaron@internet2.edu 0.01-1
- Specfile autogenerated.
