# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-DB-SQL
version:      0.02
version_from: lib/perfSONAR_PS/DB/SQL.pm
installdirs:  site
requires:
    DBI:                           1.4
    Log::Log4perl:                 1
    strict:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
