# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Topology-Common
version:      0.02
version_from: lib/perfSONAR_PS/Topology/Common.pm
installdirs:  site
requires:
    Exporter:                      0
    Log::Log4perl:                 1
    perfSONAR_PS::Common:          0.02
    strict:                        0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
