 CREATE TABLE 'pairs_200703' (
 'metaID' varchar(52)  NOT NULL,
 'pkgs_rcvd' smallint(4) unsigned NOT NULL,
 'ttl' smallint(4) unsigned,
 'numBytes' smallint(4) unsigned,
 'min_time' float,
 'avrg_time' float,
 'max_time' float,
 'timestamp' bigint(12) unsigned NOT NULL,
 'min_delay' float,
 'ipdv' float,
 'max_delay' float,
 'dupl' boolean,
 'outOfOrder' boolean,
 'median_time' float,
 'clp' float,
 'iqr_delay' float,
  'lossPercent'  float,
  PRIMARY KEY  ('metaID' ,'timestamp'));

CREATE TABLE 'metaData' (
  'metaID' varchar(52) NOT NULL,
 'ip_name_src' varchar(52),
 'ip_name_dst' varchar(52),
 'ip_number_src' varchar(15) NOT NULL,
 'ip_number_dst' varchar(15) NOT NULL,
 'pkg_size' smallint(4) unsigned NOT NULL,
 'pkgs_sent' smallint(4) unsigned NOT NULL,
 'protocol' varchar(4) NOT NULL,
 'ttl' smallint(4) unsigned,
  PRIMARY KEY  ('metaID'));
