# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Client-Status-MA
version:      0.04
version_from: lib/perfSONAR_PS/Client/Status/MA.pm
installdirs:  site
requires:
    Log::Log4perl:                 1
    perfSONAR_PS::Common:          0.04
    perfSONAR_PS::Status::Common:  0.04
    perfSONAR_PS::Status::Link:    0.04
    perfSONAR_PS::Transport:       0.04
    strict:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
