dist:
	mkdir /tmp/perfSONAR_PS-perfSONARBUOY
	tar ch -T MANIFEST | tar x -C /tmp/perfSONAR_PS-perfSONARBUOY
	tar czf perfSONAR_PS-perfSONARBUOY.tar.gz -C /tmp perfSONAR_PS-perfSONARBUOY
	rm -rf /tmp/perfSONAR_PS-perfSONARBUOY
