# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Services-LS
version:      0.06
version_from: lib/perfSONAR_PS/Services/LS/LS.pm
installdirs:  site
requires:
    Exporter:                      0
    Log::Log4perl:                 1
    perfSONAR_PS::Common:          0.06
    perfSONAR_PS::DB::XMLDB:       0.06
    perfSONAR_PS::Messages:        0.06
    perfSONAR_PS::Services::Base:  0.06
    perfSONAR_PS::Services::MA::General: 0.06
    strict:                        0
    Time::HiRes:                   1.85
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
