# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Services-LS
version:      v0.01
version_from: lib/perfSONAR_PS/Services/LS/LS.pm
installdirs:  site
requires:
    Exporter:                      0
    Log::Log4perl:                 1
    perfSONAR_PS::Common:          v0.01
    perfSONAR_PS::DB::XMLDB:       v0.01
    perfSONAR_PS::Messages:        v0.01
    perfSONAR_PS::Services::Base:  v0.01
    perfSONAR_PS::Services::MA::General: v0.01
    strict:                        0
    Time::HiRes:                   1.85
    version:                       0.5
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
