# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-DB-XMLDB
version:      0.09
version_from: lib/perfSONAR_PS/DB/XMLDB.pm
installdirs:  site
requires:
    English:                       0
    fields:                        0
    Log::Log4perl:                 1
    Params::Validate:              0.64
    perfSONAR_PS::Common:          0.09
    Sleepycat::DbXml:              2
    strict:                        0
    warnings:                      0
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
