Name:           perl-perfSONAR_PS-Collectors-Daemon
Version:        0.06
Release:        1%{?dist}
Summary:        perfSONAR_PS::Collectors::Daemon Perl module
License:        CHECK(GPL or Artistic)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/perfSONAR_PS-Collectors-Daemon/
Source0:        http://www.cpan.org/modules/by-module/perfSONAR_PS/perfSONAR_PS-Collectors-Daemon-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(Config::General) >= 2.3
Requires:       perl(Log::Log4perl) >= 1
Requires:       perl(Module::Load) >= 0.1
Requires:       perl(perfSONAR_PS::Common) >= 0.06
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The perfSONAR_PS::Collectors::Daemon is the main daemon that is used to
start perfSONAR collectors. To use the daemon, install the modules for the
collectors one is interested in and configure the services in
collector.conf.

%prep
%setup -q -n perfSONAR_PS-Collectors-Daemon-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null \;

chmod -R u+rwX,go+rX,go-w $RPM_BUILD_ROOT/*

perldoc -t perlgpl > COPYING
perldoc -t perlartistic > Artistic

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README logger.conf modules perfsonar-collector perfsonar-collector.init perl-perfSONAR_PS-Collectors-Daemon.spec psConfigureCollectors COPYING Artistic
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 28 2008 aaron@internet2.edu 0.06-1
- Specfile autogenerated.
