#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use DBI;

my $sqlite_create_status_table =<<EOQ
CREATE TABLE IF NOT EXISTS TABLEPREFIXstatus (
  id varchar(255) NOT NULL,
  start_time integer not null,
  end_time integer not null,
  oper_status varchar(32) not null,
  admin_status varchar(32) not null,
 unique (id, start_time, end_time));
EOQ
;

my $mysql_create_status_table =<<EOQ
CREATE TABLE IF NOT EXISTS TABLEPREFIXstatus (
  id varchar(255) NOT NULL,
  start_time bigint not null,
  end_time bigint not null,
  oper_status varchar(32) not null,
  admin_status varchar(32) not null,
  unique(id, start_time, end_time)
);
EOQ
;

my $CONFIG_FILE;
my $DEBUGFLAG;
my $HELP;
my $LOGGER_CONF;
my $NEW_TOPOLOGY;
my $DB_TYPE;
my $DB_PREFIX;
my $DB_HOST;
my $DB_PORT;
my $DB_NAME;
my $DB_FILE;
my $DB_USERNAME;
my $DB_PASSWORD;

my ($status, $res, $res2);

$status = GetOptions (
        'type=s' => \$DB_TYPE,
        'prefix=s' => \$DB_PREFIX,
        'file=s' => \$DB_FILE,
        'name=s' => \$DB_NAME,
        'host=s' => \$DB_HOST,
        'port=s' => \$DB_PORT,
        'username=s' => \$DB_USERNAME,
        'password=s' => \$DB_PASSWORD,
        );

if (not $DB_TYPE) {
	print "No database type specified\n";
	usage();
	exit(-1);
}

sub usage {
	print "$0: Initialize a Link Status database\n";
	print "  --type: The database type: 'sqlite' or 'mysql'\n";
	print "  --prefix: The prefix of the tables to create. defaults to 'ps_'\n";
	print "  If SQLite is chosen, you can use these arguments\n";
	print "  --file: The database file to use\n";
	print "  If MySQL is chosen, you can use these arguments\n";
	print "  --name: The database to use\n";
	print "  --host: The database host to use\n";
	print "  --port: The database port to use\n";
	print "  --username: The database username to use\n";
	print "  --password: The database password to use\n";
}

$DB_TYPE = lc($DB_TYPE);

if ($DB_TYPE ne "sqlite" and $DB_TYPE ne "mysql") {
	print "Invalid database type specified. Must be either 'mysql' or 'sqlite'\n";
	usage();
	exit(-1);
}

if (not $DB_PREFIX) {
	$DB_PREFIX= 'ps_';
}

if ($DB_TYPE eq "sqlite") {
	if (not $DB_FILE) {
		print "Need to specify a database file\n";
		usage();
		exit(-1);
	}

	my $dbi_string = "DBI:SQLite:dbname=".$DB_FILE;

	$sqlite_create_status_table =~ s/TABLEPREFIX/$DB_PREFIX/gm;

	my ($sth);

	my $dbh = DBI->connect($dbi_string);
	$sth = $dbh->prepare($sqlite_create_status_table) or die "Couldn't prepare statement: " . $dbh->errstr;
	$sth->execute();
} elsif ($DB_TYPE eq "mysql") {
        my $dbi_string = "dbi:mysql";

	if (not $DB_NAME) {
		print "Need to specify a database name\n";
		usage();
		exit(-1);
	}

	$mysql_create_status_table =~ s/TABLEPREFIX/$DB_PREFIX/gm;

	$dbi_string .= ":database=".$DB_NAME;

	if (not $DB_HOST) {
		print "Need to specify the database host\n";
		usage();
		exit(-1);
	}

	$dbi_string .= ":host=".$DB_HOST;

    if ($DB_PORT) {
        $dbi_string .= ":port=".$DB_PORT;
    }

	my $dbh = DBI->connect($dbi_string);
	my $sth2 = $dbh->prepare($mysql_create_status_table, $DB_USERNAME, $DB_PASSWORD) or die "Couldn't prepare statement: " . $dbh->errstr;
	$sth2->execute();
}
