Name:           perl-perfSONAR_PS-Services-Daemon
Version:        v0.01
Release:        1%{?dist}
Summary:        perfSONAR_PS::Services::Daemon Perl module
License:        distributable, see LICENSE
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/perfSONAR_PS-Services-Daemon/
Source0:        http://www.cpan.org/modules/by-module/perfSONAR_PS/perfSONAR_PS-Services-Daemon-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(Config::General) >= 2.3
Requires:       perl(HTTP::Daemon) >= 1.35
Requires:       perl(Log::Log4perl) >= 1
Requires:       perl(Module::Load) >= 0.1
Requires:       perl(Params::Validate) >= 0.7
Requires:       perl(XML::LibXML) >= 1.6
Requires:       perl(XML::XPath) >= 1.13
Requires:       perl(perfSONAR_PS::Common) >= v0.01
Requires:       perl(perfSONAR_PS::Error_compat) >= v0.01
Requires:       perl(perfSONAR_PS::Messages) >= v0.01
Requires:       perl(perfSONAR_PS::XML::Document_string) >= v0.01
Requires:       perl(version) >= 0.5
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The perfSONAR_PS::Services::Daemon is the main daemon that is used to start
the perfSONAR services. To use the daemon, install the modules for the
services one is interested in and configure the services in perfsonar.conf.

%prep
%setup -q -n perfSONAR_PS-Services-Daemon-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null \;

chmod -R u+rwX,go+rX,go-w $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README logger.conf psConfigureDaemon
%{_bindir}/*
%{_mandir}/man1/*
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 04 2008 aaron@internet2.edu v0.01-1
- Specfile autogenerated.
