# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-DB-File
version:      0.04
version_from: lib/perfSONAR_PS/DB/File.pm
installdirs:  site
requires:
    Data::Compare:                 0
    Log::Log4perl:                 1
    strict:                        0
    Test::More:                    0
    warnings:                      0
    XML::LibXML:                   1.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
