# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         perfSONAR_PS-Collectors-LinkStatus
version:      0.06
version_from: lib/perfSONAR_PS/Collectors/LinkStatus.pm
installdirs:  site
requires:
    Exporter:                      0
    fields:                        0
    Log::Log4perl:                 1
    Net::SNMP:                     5.0.0
    perfSONAR_PS::Client::Status::MA: 0.06
    perfSONAR_PS::Collectors::Base: 0.06
    perfSONAR_PS::Common:          0.06
    perfSONAR_PS::DB::File:        0.06
    perfSONAR_PS::Status::Common:  0.06
    strict:                        0
    Time::HiRes:                   1.85
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
