#!/bin/bash
#
# Init file for perfSONAR TL1 Collector
#
# chkconfig: 2345 60 20
# description: perfSONAR TL1 Collector
#

PREFIX=/opt/perfsonar_ps/tl1_service
BINDIR=${PREFIX}/bin
CONFDIR=${PREFIX}/etc
RUNDIR=/var/run

CONFFILE=${CONFDIR}/collector.conf
LOGGERFILE=${CONFDIR}/collector_logger.conf
PIDFILE=tl1_collector.pid

USER=perfsonar
GROUP=perfsonar

FULL_PIDFILE=${RUNDIR}/tl1_collector.pid

PERFSONAR="${BINDIR}/collector.pl --config=${CONFFILE} --pidfile=${PIDFILE} --piddir=${RUNDIR} --logger=${LOGGERFILE} --user=${USER} --group=${GROUP}"

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    # check for pidfile
    if [ -f $FULL_PIDFILE ] ; then
        PID=`cat $FULL_PIDFILE`
        if [ "x$PID" != "x" ] && kill -0 $PID 2>/dev/null ; then
            STATUS="TL1 Collector (pid $PID) running"
            RUNNING=1
        else
            STATUS="TL1 Collector (pid $PID?) not running"
            RUNNING=0
        fi
    else
        STATUS="TL1 Collector (no pid file) not running"
        RUNNING=0
    fi 

    case $ARG in
    start)
	echo $PERFSONAR

	if $PERFSONAR ; then
	    echo "$0 $ARG: TL1 Collector started"
	else
	    echo "$0 $ARG: TL1 Collector could not be started"
	    ERROR=3
	fi
	;;
    stop)
	if [ $RUNNING -eq 0 ]; then
	    echo "$0 $ARG: $STATUS"
	    continue
	fi
	if kill $PID ; then
	    echo "$0 $ARG: TL1 Collector stopped"
	else
	    echo "$0 $ARG: TL1 Collector could not be stopped"
	    ERROR=4
	fi
	;;
    restart)
    	$0 stop; echo "waiting..."; sleep 10; $0 start;
	;;
    *)
	echo "usage: $0 (start|stop|restart|help)"
	cat <<EOF

start      - start TL1 Collector
stop       - stop TL1 Collector
restart    - restart TL1 Collector if running by sending a SIGHUP or start if 
             not running
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR
